apiVersion: v1
kind: Secret
metadata:
  annotations:
    kubernetes.io/service-account.name: addon-operator-prom-token
  labels:
    name: addon-operator
  name: addon-operator-prom-token
type: kubernetes.io/service-account-token
