apiVersion: v1
kind: ServiceAccount
metadata:
  name: addon-operator-prom-token
  namespace: openshift-addon-operator  
  annotations:
    kubernetes.io/service-account.name: "addon-operator-prom-token"
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    kubernetes.io/service-account.name: addon-operator-prom-token
  labels:
    name: addon-operator
  name: addon-operator-prom-token
  namespace: openshift-addon-operator
type: kubernetes.io/service-account-token    
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: addon-operator-prom-token-role
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: addon-operator-prom-token-role-binding
subjects:
- kind: ServiceAccount
  name: addon-operator-prom-token
  namespace: openshift-addon-operator
roleRef:
  kind: ClusterRole
  name: addon-operator-prom-token-role
  apiGroup: rbac.authorization.k8s.io
